### ISSUE TITLE
Is it possible to run vectrex games ?

### ISSUE THREAD

**Issue by faxm0dem** [malbanGit/pitrex-baremetal#1]
Is it possible to run vectrex ROMs ?
I know the pitrex is about emulating other systems, but it would be cool if there were a pass-through mode that allows vectrex games to be played

**Comment by amaiorano** [comment]
The pitrex has a Vectrex emulator that emulates the CPU and RAM, while forwarding the drawing and audio to the real hardware.

The pitrex cannot, however, emulate being a Vectrex **cart** and allow the real CPU to execute because it does not tap into the entire address bus, as I understand it.

**Comment by faxm0dem** [comment]
Thank you for this information.
Where do I have to put the `.vec` files ?

**Comment by amaiorano** [comment]
From [this page on Malban's blog](http://vide.malban.de/pitrex/pitrex-baremetal-quick-start-unfinished) you'll see the link to the [FAQ here](http://vectrex.malban.de/pitrex/PiTrexBM_FAQ.txt) with the answer to your question:

```
15) Where can I put my own vectrex roms/binaries?
#################################################
The exact vectrex emulator can load roms from the SD card,
the roms must be placed into folder: "/vectrex" and should have
the "bin" extension.
```

Hope this helps!

**Comment by faxm0dem** [comment]
thanks !
